// SPDX-License-Identifier: AGPL-3.0-or-later

package es.uvigo.esei.sing.vacbot.settings;

import java.nio.file.Path;

import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import lombok.AccessLevel;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.NonNull;
import lombok.ToString;

/**
 * Contains all the settings related to the knowledge base of documents to be
 * used with VacBot. This knowledge base is assumed to be generated by TextProc.
 *
 * @author Alejandro González García
 * @see VacBotSettings
 */
@XmlRootElement(name = "knowledgeBaseConnection")
@NoArgsConstructor(access = AccessLevel.PRIVATE)
@ToString
public final class KnowledgeBaseConnectionSettings {
	/**
	 * The directory where the KB resides.
	 */
	@Getter @NonNull
	@XmlElement(name = "directory", required = true)
	@XmlJavaTypeAdapter(CommonJAXBAdapters.DirectoryAdapter.class)
	private final Path directory = null;
}
