name: Maven CI

on: [push, pull_request]

jobs:
  build:

    strategy:
      fail-fast: true
      max-parallel: 1
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Set up Maven repository cache
      uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Setup JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Generate artifact with Maven
      run: mvn package
      env:
        GITHUB_TOKEN: ${{ github.token }}
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: VacBot-${{github.sha}}.zip
        # Directory containing files to upload
        path: dist
